version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doubt-front
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
